export const queryKeys = {
  auth: ["identity", "session"] as const,
  users: ["identity", "users"] as const,
  guardrails: ["resources", "guardrails"] as const,
  guardrail: (id: string) => ["resources", "guardrails", id] as const,
  guardrailDeletionImpact: (id: string) => ["resources", "guardrails", id, "deletion-impact"] as const,
  guardrailLogging: (id: string) => ["resources", "guardrails", id, "logging"] as const,
  guardrailFindings: (id: string, window: string) => ["resources", "guardrails", id, "findings", { window }] as const,
  guardrailVersions: (id: string) => ["resources", "guardrail-versions", id] as const,
  guardrailVersion: (id: string, version: string) => ["resources", "guardrail-versions", id, version] as const,
  policies: ["resources", "policies"] as const,
  policy: (id: string) => ["resources", "policies", id] as const,
  actionCatalog: ["resources", "actions"] as const,
  intentAnalysisStatus: ["resources", "intent-analysis-status"] as const,
  playgroundModels: ["resources", "playground-models"] as const,
  playgroundDraftPreview: (guardrailId: string, draftRevision: number) => ["resources", "playground-draft-preview", guardrailId, draftRevision] as const,
  playgroundSession: (guardrailId: string, targetKey: string) => ["resources", "playground-session", guardrailId, targetKey] as const,
  validationRuns: (guardrailId: string) => ["resources", "validation-runs", { guardrailId }] as const,
  allValidationRuns: ["resources", "validation-runs"] as const,
  validationRun: (runId: string) => ["resources", "validation-runs", runId] as const,
  testCases: (guardrailId: string) => ["resources", "test-cases", { guardrailId }] as const,
  deployments: ["resources", "deployments"] as const,
  deployment: (id: string) => ["resources", "deployments", id] as const,
  deploymentDeletionImpact: (id: string) => ["resources", "deployments", id, "deletion-impact"] as const,
  deploymentTraces: (id: string) => ["resources", "deployments", id, "traces"] as const,
  trafficScopeFields: ["resources", "traffic-scope-fields"] as const,
  integrations: ["resources", "integrations"] as const,
  integration: (id: string) => ["resources", "integrations", id] as const,
  integrationDeletionImpact: (id: string) => ["resources", "integrations", id, "deletion-impact"] as const,
  evidence: ["resources", "evidence"] as const,
  runtimeLogs: (filters: { guardrailId?: string; phase?: string; outcome?: string; window: string }) => ["resources", "runtime-logs", filters] as const,
  metrics: ["resources", "metrics"] as const,
  metricsScope: (filters: { guardrailId?: string; deploymentId?: string; window: string }) => ["resources", "metrics", filters] as const,
  systemStatus: ["resources", "system-status"] as const,
};
