export const queryKeys = {
  auth: ["identity", "session"] as const,
  users: ["identity", "users"] as const,
  guardrails: ["resources", "guardrails"] as const,
  guardrail: (id: string) => ["resources", "guardrails", id] as const,
  guardrailDeletionImpact: (id: string) => ["resources", "guardrails", id, "deletion-impact"] as const,
  guardrailLogging: (id: string) => ["resources", "guardrails", id, "logging"] as const,
  guardrailFindings: (id: string, window: string) => ["resources", "guardrails", id, "findings", { window }] as const,
  guardrailVersions: (id: string) => ["resources", "guardrail-versions", id] as const,
  guardrailVersion: (id: string, version: string) => ["resources", "guardrail-versions", id, version] as const,
  policies: ["resources", "policies"] as const,
  protectionPresets: ["resources", "protection-presets"] as const,
  policy: (id: string) => ["resources", "policies", id] as const,
  actionCatalog: ["resources", "actions"] as const,
  intentAnalysisStatus: ["resources", "intent-analysis-status"] as const,
  playgroundModels: ["resources", "playground-models"] as const,
  playgroundDraftPreview: (guardrailId: string, draftRevision: number) => ["resources", "playground-draft-preview", guardrailId, draftRevision] as const,
  playgroundSession: (guardrailId: string, targetKey: string) => ["resources", "playground-session", guardrailId, targetKey] as const,
  validationRuns: (guardrailId: string) => ["resources", "validation-runs", { guardrailId }] as const,
  allValidationRuns: ["resources", "validation-runs"] as const,
  validationRun: (runId: string) => ["resources", "validation-runs", runId] as const,
  testCases: (guardrailId: string) => ["resources", "test-cases", { guardrailId }] as const,
  routers: ["resources", "routers"] as const,
  router: (id: string) => ["resources", "routers", id] as const,
  routerDeletionImpact: (id: string) => ["resources", "routers", id, "deletion-impact"] as const,
  routerTraces: (id: string, limit: number) => ["resources", "routers", id, "traces", { limit }] as const,
  trafficScopeFields: ["resources", "traffic-scope-fields"] as const,
  endpoints: ["resources", "endpoints"] as const,
  endpoint: (id: string) => ["resources", "endpoints", id] as const,
  endpointDeletionImpact: (id: string) => ["resources", "endpoints", id, "deletion-impact"] as const,
  runtimeEvents: ["resources", "runtime-events"] as const,
  runtimeEventsScope: (filters: { guardrailId?: string; window: string; limit: number }) => ["resources", "runtime-events", filters] as const,
  auditEvents: ["resources", "audit-events"] as const,
  metrics: ["resources", "metrics"] as const,
  metricsScope: (filters: { guardrailId?: string; routerId?: string; window: string }) => ["resources", "metrics", filters] as const,
  systemStatus: ["resources", "system-status"] as const,
};
