/** Business semantics supplement generated structural schemas. These names are independent of token scopes. */
export const apiTags = [
  ['account', 'Account', 'Authenticated identity and effective permissions.'],
  ['access-tokens', 'Account', 'Personal credential lifecycle; browser session required.'],
  ['guardrails', 'Guardrail Design', 'Guardrail drafts, immutable versions and release lifecycle.'],
  ['policies', 'Guardrail Design', 'Reusable Policies and their published versions.'],
  ['testing', 'Guardrail Design', 'Test Cases and Test Runs that check Guardrail/Policy Rule behavior against expected results.'],
  ['authoring', 'Guardrail Design', 'Intent analysis, document analysis and proposed plans.'],
  ['playground', 'Guardrail Design', 'Draft and published Guardrail interactions.'],
  ['routers', 'Integration', 'Router drafts, publication, simulation and Endpoint bindings.'],
  ['endpoints', 'Integration', 'Endpoint identities and runtime credentials.'],
  ['telemetry', 'Observability', 'Controller runtime observations and traffic statistics; not Runner invocation APIs.'],
  ['audit', 'Observability', 'Control-plane audit events.'],
  ['model-providers', 'Platform Settings', 'Provider connections, discovery and combined model registration.'],
  ['models', 'Platform Settings', 'Registered Model definitions, connection tests and capability tests.'],
  ['model-configurations', 'Platform Settings', 'Model assignments, validation evidence and activation.'],
  ['runners', 'Platform Settings', 'Runner capacity and instance lifecycle.'],
  ['system', 'Platform Settings', 'Component health, software identities and public runtime readiness.'],
].map(([name, area, description]) => ({ name: name!, description: description!, 'x-product-area': area! }));

export function operationContract(method: string, path: string) {
  const tag = path.includes('/access-tokens') ? 'access-tokens' : path.includes('/account/') ? 'account'
    : path.includes('/authoring/') ? 'authoring' : path.includes('/playground/') ? 'playground'
    : path.includes('/model-configuration') ? 'model-configurations' : path.includes('/model-provider') ? 'model-providers'
    : path.includes('/models') ? 'models' : path.includes('/test-cases') || path.includes('/test-runs') || path.includes('/test-scope') ? 'testing'
    : path.includes('/telemetry/') || path.endsWith('/traffic-distribution') ? 'telemetry'
    : path.includes('/routers') || path.includes('/routing/') ? 'routers' : path.includes('/endpoints') ? 'endpoints'
    : path.includes('/policies') || path.includes('/policy-catalog') ? 'policies'
    : (path.includes('/guardrails') || path.includes('/guardrail-profiles') || path.includes('/guardrail-packages')) ? 'guardrails' : path.includes('/runner-') ? 'runners' : path.includes('/audit-events') ? 'audit' : 'system';
  const terminal = path.split('/').at(-1)!;
  const noun = (terminal.startsWith(':') ? path.split('/').at(-2)! : terminal).replaceAll('-', ' ');
  let summary = `${({ GET: 'Read', POST: 'Create', PUT: 'Replace', PATCH: 'Update', DELETE: 'Delete' } as Record<string, string>)[method]} ${noun}`;
  let description = method === 'GET' ? 'Reads current state without creating resources or advancing a lifecycle.'
    : method === 'DELETE' ? 'Removes only the resource identified by this path. An already absent resource may return 404.'
    : method === 'PUT' ? 'Replaces the addressed configuration. Review current state before overwriting concurrent changes.'
    : method === 'PATCH' ? 'Updates the supplied fields; omitted fields are retained. Validation or draft state may be invalidated.'
    : 'Creates a resource or executes the named operation. A network failure does not prove that execution failed.';
  let mode = method === 'GET' ? 'safe-read' : method === 'DELETE' || method === 'PUT' ? 'idempotent-effect' : 'not-guaranteed';
  let retry = method === 'GET' || method === 'DELETE' ? 'Repeat the same request; the response may reflect newer state or absence.' : 'Do not automatically retry an uncertain write. Read its result or current resource first.';
  let details: Record<string, unknown> = {};
  if (path === '/api/v1/guardrails/:id/draft-changes') { summary = 'Compare the working draft with the latest published baseline'; description += ' Reports meaningful configuration and test changes, ignoring persistence timestamps and object key order. Older versions without a complete source snapshot cannot be restored.'; }
  if (path === '/api/v1/guardrails/:id/discard-draft') { summary = 'Discard unpublished Guardrail changes'; description += ' Requires the reviewed expectedDraftRevision and expectedBaselineVersion. Restores configuration, custom and inherited test cases, and exclusions from the published source snapshot. Increments the draft revision, retains test reports and audit history, and does not change published versions or routing. Returns 409 if the draft/baseline changed or compilation is pending.'; }
  if (path === '/api/v1/system/health') { summary = 'Read control-plane and data-plane component health'; description += ' Checks Controller storage access and connection/heartbeat evidence for all registered Runners. Guardrail publication, model bindings, assignments, configuration generation and desired pool capacity do not affect this component-liveness result. HTTP 200 returns the completed snapshot even when a component is unhealthy; a failed Controller storage check leaves data-plane health unknown.'; }
  if (method === 'DELETE' && path === '/api/v1/runner-instances/:runnerId') { description += ' By default only offline registrations can be removed. force=true with the observed bootId also permits initializing/syncing registrations and closes the matching control connection. Serving Runners remain protected; changed state or boot identity returns 409. Does not stop the process or delete a Pod; a running Runner may register again.'; retry = 'Refresh Runner state after an uncertain response. A reconnect may create a new registration.'; }
  if (path.endsWith('/connection-tests')) { summary = 'Test connection and basic model invocation'; description += ' Stores connection evidence; it does not certify Guardrail capability or protocol correctness. Repeating can make another upstream call.'; }
  if (path.endsWith('/capability-tests')) { summary = 'Test model capability and protocol'; description += ' Stores capability evidence, separately from basic connection health. Repeating performs another probe.'; }
  if (path.includes('/model-provider-discoveries') || path.endsWith('/model-discoveries')) { summary = 'Discover available provider models'; description += ' Queries the provider catalog without registering resources. Draft discovery receives credentials in the body; existing-provider discovery uses stored credentials.'; }
  if (path.endsWith('/model-provider-registrations')) { summary = 'Register a provider and selected models'; description += ' Probes connections, then stores the provider and selected definitions in one database transaction. Capability validation remains a separate step.'; }
  if (path.endsWith('/draft/checks')) { summary = 'Read Policy draft checks and validation status'; description += ' Checks metadata and reads existing execution evidence; does not enqueue a Runner validation.'; }
  if (path.endsWith('/publication-preview')) { summary = 'Preview the exact Router publication'; description += ' Resolves targets that use latest to the Latest version of each Guardrail, plus the bound Endpoints, for the expectedDraftRevision without publishing. Send snapshot and endpointIds back as reviewedSnapshot and reviewedEndpointIds when submitting a change request.'; mode = 'read-only-computation'; retry = 'May repeat; referenced versions or Endpoint bindings may have changed. Review the new result.'; }
  if (path === '/api/v1/playground/path-tests') { summary = 'Test Router routing or execute a Runner Endpoint request'; description += ' Published Router probes run on the configured Runner with a revision fence. Drafts only simulate selectors. Endpoint requests use the fixed Runner origin and supplied Endpoint credentials, not external Ingress. No arbitrary URL forwarding.'; retry = 'Simulation may repeat. Execution can incur model work; inspect the result before retrying.'; }
  if (path.endsWith('/simulations')) { summary = 'Simulate request matching against a Router draft'; description += ' Evaluates supplied draft and input without publishing or executing a Guardrail.'; mode = 'read-only-computation'; retry = 'May repeat with the same input.'; }
  if (path.endsWith('/traffic-distribution')) { summary = 'Read historical traffic distribution'; description += ' Reports request counts, decisions and trends. It is not configuration rollout status; inspect GET /routers/{id} rolloutStatus and desiredGeneration for rollout.'; }
  if (method === 'PUT' && path.endsWith('/endpoints')) { summary = 'Replace the Router Endpoint binding set'; description += ' An identical normalized set is a no-op: no new generation or redistribution. A changed set takes effect through desired-state distribution.'; }
  if (method === 'PUT' && path === '/api/v1/routers/:id/draft') { mode = 'conditional-replacement'; description += ' expectedDraftRevision is a concurrency precondition. Repeating a successful save with the old revision returns 409; this does not mean the first save failed.'; retry = 'GET the draft and compare contents after uncertainty; never substitute a newer expectedDraftRevision without review.'; }
  if (path.includes('/candidate-validations')) { summary = method === 'GET' ? 'Read candidate model validation evidence' : 'Validate a candidate model before assigning it'; description += ' Evidence is persisted across Controller instances, belongs to the authenticated account and target/model, and is valid for 10 minutes. POST returns validationId and expiresAt. It does not save the assignment. Pass validationId to the assignment PUT. Changed provider/model settings invalidate evidence.'; }
  if (method === 'PUT' && path.includes('/assignments/:target')) { description += ' Assigning a different non-null model requires a successful unexpired validationId for this account, target and unchanged model. Identical assignments are no-ops. Clearing uses modelId:null.'; }
  if (method === 'PUT' && path === '/api/v1/model-configuration/draft') { description += ' Replaces all assignments and clears validation only when assignments change. It does not certify the replacement; run draft validations before activation.'; }
  if (path.endsWith('/validations') && !path.includes('candidate-validations')) { summary = 'Validate saved model assignments'; description += ' Validates the currently saved target or whole draft; candidate model IDs are not accepted by this operation.'; }
  if (method === 'POST' && path.endsWith('/test-runs')) { summary = 'Start a Test Run'; description += ' Creates a new Runner task on each request. Track the returned run ID rather than latest, which can change when another task is created.'; }
  if (path === '/api/v1/routers/:id/change-requests' && method === 'POST') { summary = 'Submit a reviewed Router change for approval'; description += ' Freezes the reviewed snapshot, with latest Guardrail versions already resolved, and the bound Endpoint set. Nothing is published until another administrator approves it. expectedDraftRevision prevents stale submission; a Router has at most one pending change request (409 router_change_request_pending).'; retry = 'After uncertainty, read GET /routers/{id}; pendingChangeRequest identifies a submission that succeeded.'; }
  if (path.endsWith('/change-requests/:changeId/approve')) { summary = 'Approve and apply a pending Router change'; description += ' The approver must differ from the submitter. Applies exactly the frozen snapshot as a new Router revision and starts distribution; 202 confirms the revision, not Runner readiness. If the active revision, bound Endpoints or referenced versions changed, the request becomes superseded and 409 router_change_request_stale is returned. Approval also pre-approves reverting to the base revision.'; mode = 'state-transition'; retry = 'The same approver may repeat the request; an applied request returns publication.replayed=true without another revision.'; }
  if (path.endsWith('/change-requests/:changeId/emergency-apply')) { summary = 'Apply a pending Router change without a second approver'; description += ' For emergencies only. Requires a reason and a manager contact, both recorded on the change request and in audit history. Validation and staleness rules are the same as approval.'; mode = 'state-transition'; retry = 'The same administrator may repeat the request; an applied request returns publication.replayed=true.'; }
  if (path.endsWith('/change-requests/:changeId/reject')) { summary = 'Reject a pending Router change'; description += ' Another administrator closes the request with a required note. Nothing is published.'; }
  if (path.endsWith('/change-requests/:changeId/withdraw')) { summary = 'Withdraw your pending Router change'; description += ' Only the submitter can withdraw. Nothing is published.'; }
  if (path.endsWith('/change-requests/:changeId/revert')) { summary = 'Revert the active change to its approved base revision'; description += ' Available only while the change still produced the active revision. Publishes the base revision again as a new revision without another approval, records a revert change request, and supersedes any pending change.'; retry = 'Do not repeat blindly: after success the change is no longer active and a repeat returns 409. Read GET /routers/{id} first.'; }
  if (path.endsWith('/duplicate')) { mode = 'keyed'; summary = 'Copy a Guardrail source into a new Guardrail'; description += ' Choose sourceVersion or sourceDraftRevision. An absent source defaults to the active version. Replays return the current copied resource.'; details = { key: 'body.idempotencyKey', scope: 'actorId across Guardrail copy requests', retention: 'No time expiry; bound to the copied resource, including its soft-deletion record.', requestComparison: 'Source Guardrail ID, name and requested source version/draft revision.', conflictStatus: 409, concurrentDuplicates: 'Serialized by actor/key.', replay: 'Current copied resource; deleted copy returns not found without recreating it.' }; retry = 'Repeat the original key and body; do not create a new key merely because the response was lost.'; }
  if (path === '/api/v1/policies/:id/publish') { mode = 'revision-keyed'; summary = 'Publish a validated Policy draft'; description += ' expectedDraftRevision is required. The same Policy and source draft revision reuse the existing immutable published version.'; retry = 'Repeat the same expectedDraftRevision; a different revision is a different publication.'; }
  if (path === '/api/v1/guardrails/:id/publish') { summary = 'Publish the tested Guardrail candidate'; description += ' expectedDraftRevision is required. Publishes exactly the Artifact that the latest passed test run of that revision compiled and executed, signed by this environment; nothing is recompiled. Publishing the same tested revision again returns the existing version.'; }
  if (path === '/api/v1/guardrails/:id/package') { summary = 'Download a signed Guardrail release package'; description += ' versions is a comma-separated list of published versions (default: Latest). Returns a .guardrail.zip containing, per version, the exact Artifact content, its frozen inspection snapshot, derived runtime requirements and the test evidence for that content digest, signed with this environment\'s package key. Versions without tested-candidate evidence or complete Policy snapshots return 409 guardrail_package_incomplete with the missing items per version. No credentials, Routers, Endpoints or model bindings are included.'; }
  if (method === 'POST' && path === '/api/v1/guardrail-packages') { mode = 'content-keyed'; summary = 'Upload and verify a Guardrail release package'; description += ' Verifies archive safety, every file digest, the signature against this environment\'s configured trusted sources, and each version\'s content digest and evidence. Stores the exact bytes (packageId is their SHA-256) and returns a preview: per version new/existing/conflict, test evidence, requirements and a Runner load check. Nothing is imported.'; retry = 'Uploading the same bytes again returns the same packageId.'; }
  if (path === '/api/v1/guardrail-packages/:packageId') { summary = 'Preview an uploaded Guardrail release package'; description += ' Re-verifies the stored package against current trust configuration and current versions.'; }
  if (path === '/api/v1/guardrail-packages/:packageId/imports') { mode = 'content-keyed'; summary = 'Import versions from a verified package'; description += ' Appends the selected versions (default: all) in one transaction after re-verifying the stored bytes. Identical versions already present are reported as existing; any version with the same number but different content returns 409 guardrail_version_conflict and nothing is written. Does not change Routers, Endpoints, traffic or the runtime baseline; the first import sets Latest to the recommended version.'; retry = 'Repeating the import reports already-imported versions as existing.'; }
  if (path === '/api/v1/guardrails/:id/versions/:version/environment-check') { summary = 'Check whether this environment can serve a version'; description += ' Asks one connected Runner in every pool to verify the signed Artifact and build its runtime with current software, Actions and models, without serving it. compatible means every pool admitted it; missing lists rejections; pending means no Runner answered.'; }
  if (path === '/api/v1/guardrails/:id/versions/:version/deletion-impact') { summary = 'Check whether a Guardrail version can be deleted'; description += ' Lists what still depends on the immutable version: the Latest pointer, active Router revisions, edited Router drafts, pending change requests and the pre-approved rollback target. Blockers report calls that may still be running after the version left routing. unrestorableRevisions lists historical Router revisions that remain for audit but can no longer be restored.'; }
  if (method === 'DELETE' && path === '/api/v1/guardrails/:id/versions/:version') { summary = 'Delete an immutable Guardrail version'; description += ' Allowed only when the deletion impact is deletable; otherwise returns 409 version_in_use with the impact in error.detail. The compiled Artifact and telemetry are retained for audit.'; }
  if (path === '/api/v1/guardrails/:id/latest-version') { summary = 'Mark an immutable Guardrail version as latest'; description += ' version must identify a ready compiled version. Moves the Latest pointer to that existing version without compiling or creating another version; publishing a new version moves it automatically. Router targets with versionStrategy=latest resolve to this pointer when a routing change is submitted, so traffic does not change until such a change is approved. Repeating for the current latest version is a no-op.'; }
  if (path === '/api/v1/guardrails/:id/versions/:version/export') { summary = 'Download a compiled Guardrail Artifact'; description += ' Returns the ready version as an attachment in tasklattice.guard.control.v1.Artifact Protobuf JSON format, including frozen Policy implementations, prompts, dependencies, checksum and signature. Does not compile the draft or read Policy Library. Requires a compatible TaskLattice Runner runtime and separately configured models/credentials. Versions without complete Policy snapshots return 409.'; }
  if (path.endsWith('/test-runs/latest')) { summary = 'Read the most recent Policy Test Run'; description += ' The target can change when another run starts. To track your request, use the returned runId on /policies/{id}/test-runs/{runId}.'; }
  if (path === '/api/v1/model-configuration/apply') { summary = 'Apply selected model configuration changes'; description += ' Requires bindingIds, expectedDraftToken (from draft.reviewToken) and expectedActiveId. Applies only selected changes with Runner Rail evidence; explicit removals are allowed. Unselected bindings retain current values, and pending edits remain saved. Stale reviews and in-flight applies return 409. 200 means Runner synchronization completed; 202 means still syncing, not yet globally effective. Replaces current configuration after acknowledgement; no version history or rollback is retained. Read GET /model-configuration before retrying.'; }
  if (path.endsWith('/account/identity')) { summary = 'Read the current identity and effective permissions'; }
  if (path.includes('/access-tokens')) { description += ' Browser session only. Revocation is a no-op when already revoked. Creation returns the secret once; it cannot be recovered or transparently replayed.'; }
  return { tags: [tag], summary, description, 'x-product-area': apiTags.find(item => item.name === tag)!['x-product-area'], 'x-idempotency': { mode, ...details }, 'x-retry-policy': retry };
}
