/**
 * @generated by scripts/generate_enforcement_action_contract.py
 * Source: proto/tasklattice/guard/control/v1/enforcement_action.proto
 *
 * Closed post-evaluation directives shared by Controller and Runner. This is not an evaluator verdict, a PolicyDecision, or a NeMo Action. Declaration order is the stable product display order. Non-zero numeric values are the canonical conflict priority: when independent evaluators request different actions, the action with the greatest number wins.
 * Do not edit this file directly.
 */

/**
 * Closed wire values in stable product display order. This is a
 * post-evaluation directive, not a NeMo Action or verdict.
 */
export const enforcementActions = Object.freeze([
  "reject",
  "redact",
  "rewrite",
  "regenerate",
  "redirect",
  "fallback",
  "clarify",
  "pass",
] as const);

export type EnforcementAction = typeof enforcementActions[number];

/** Stable order for UI controls and documentation; it has no conflict semantics. */
export const enforcementActionDisplayOrder = enforcementActions;

/** Canonical precedence used when independent evaluators request different actions. */
export const enforcementActionConflictOrder = Object.freeze([
  "reject",
  "clarify",
  "fallback",
  "regenerate",
  "rewrite",
  "redirect",
  "redact",
  "pass",
] as const satisfies readonly EnforcementAction[]);

/** Human-readable contract semantics; UI translations may provide localized labels. */
export const enforcementActionDescriptions = Object.freeze({
  reject: "Block the current phase. Do not call the model for rejected input or deliver rejected output.",
  redact: "Mask sensitive spans with reviewed replacements and continue with the transformed content.",
  rewrite: "Replace the current content with a complete reviewed replacement.",
  regenerate: "Ask the owner of the model lifecycle to generate a new response.",
  redirect: "Guide the interaction to an approved topic, flow, or replacement response.",
  fallback: "Use an approved fallback response or degraded execution path.",
  clarify: "Require more information from the user before the interaction continues.",
  pass: "Record the finding without intervening in the content.",
} as const satisfies Readonly<Record<EnforcementAction, string>>);

/** Numeric form of the conflict order for logs, sorting, and contract inspection. */
export const enforcementActionConflictPriorities = Object.freeze({
  reject: 800,
  redact: 200,
  rewrite: 400,
  regenerate: 500,
  redirect: 300,
  fallback: 600,
  clarify: 700,
  pass: 100,
} as const satisfies Readonly<Record<EnforcementAction, number>>);
