/**
 * @generated by scripts/generate_enforcement_action_contract.py
 * Source: proto/tasklattice/guard/control/v1/enforcement_action.proto
 *
 * Closed Rule handling decisions shared by Controller and Runner. Detector implementation and application workflows are separate from these decisions. Declaration order is display order; the greatest numeric priority wins.
 * Do not edit this file directly.
 */

/**
 * Closed wire values in stable product display order. This is a
 * post-evaluation directive, not a NeMo Action or verdict.
 */
export const enforcementActions = Object.freeze([
  "allow",
  "block",
  "transform",
] as const);

export type EnforcementAction = typeof enforcementActions[number];

/** Stable order for UI controls and documentation; it has no conflict semantics. */
export const enforcementActionDisplayOrder = enforcementActions;

/** Canonical precedence used when independent evaluators request different actions. */
export const enforcementActionConflictOrder = Object.freeze([
  "block",
  "transform",
  "allow",
] as const satisfies readonly EnforcementAction[]);

/** Human-readable contract semantics; UI translations may provide localized labels. */
export const enforcementActionDescriptions = Object.freeze({
  allow: "Keep the content unchanged and record evidence; never override another Rule's block.",
  block: "Stop the checked content. The caller owns refusal presentation and any subsequent workflow.",
  transform: "Continue only with a concrete replacement or valid content patches; missing output fails closed.",
} as const satisfies Readonly<Record<EnforcementAction, string>>);

/** Numeric form of the conflict order for logs, sorting, and contract inspection. */
export const enforcementActionConflictPriorities = Object.freeze({
  allow: 100,
  block: 800,
  transform: 200,
} as const satisfies Readonly<Record<EnforcementAction, number>>);
