# yaml-language-server: $schema=../../../schemas/rule.schema.json
id: sql-injection-blocker/blocked-word-7
name: 1=1; --
description: SQL injection
stages:
- input
- output
detector:
  ref: text/keyword
  version: 1.0.0
  parameters:
    keywords:
    - - 1=1; --
      - medium
on_match:
  action: block
  replacement: null
runtime_adapter:
  binding_id: local-sql-injection
  implementation_rule_id: blocked-word-7
metadata:
  taxonomy_ids:
  - TALI-TOOL-SECURITY-UNAUTHORIZED-EXECUTION
risk_level: high
