/**
 * Deployment capability of every API route. With authoring disabled (a
 * production that only receives released packages), only "core" routes are
 * served; everything else, including any route missing from this list,
 * returns 403 authoring_disabled. Hiding UI entries is never the control.
 */
export const routeCapabilities: ReadonlyArray<readonly [string, string, "core" | "authoring"]> = [
  ["GET", "/api/v1/system/status", "core"],
  ["GET", "/api/v1/system/health", "core"],
  ["GET", "/api/v1/system/version", "core"],
  ["GET", "/api/v1/deployment/capabilities", "core"],
  ["GET", "/api/v1/system/baseline", "core"],
  ["PUT", "/api/v1/system/baseline", "core"],
  ["GET", "/api/v1/account/access-tokens", "core"],
  ["POST", "/api/v1/account/access-tokens", "core"],
  ["DELETE", "/api/v1/account/access-tokens/:id", "core"],
  ["GET", "/api/v1/account/identity", "core"],
  // Model configuration: production binds its own models to released versions.
  ["GET", "/api/v1/model-configuration", "core"],
  ["POST", "/api/v1/model-providers", "core"],
  ["PATCH", "/api/v1/model-providers/:id", "core"],
  ["POST", "/api/v1/model-provider-discoveries", "core"],
  ["POST", "/api/v1/model-provider-registrations", "core"],
  ["POST", "/api/v1/model-providers/:id/connection-tests", "core"],
  ["POST", "/api/v1/model-providers/:id/model-discoveries", "core"],
  ["DELETE", "/api/v1/model-providers/:id", "core"],
  ["GET", "/api/v1/model-providers", "core"],
  ["GET", "/api/v1/models", "core"],
  ["POST", "/api/v1/models", "core"],
  ["POST", "/api/v1/models/:id/capability-tests", "core"],
  ["POST", "/api/v1/models/:id/connection-tests", "core"],
  ["PUT", "/api/v1/models/:id/protocol", "core"],
  ["DELETE", "/api/v1/models/:id", "core"],
  ["PUT", "/api/v1/model-configuration/draft", "core"],
  ["PUT", "/api/v1/model-configuration/draft/assignments/:target", "core"],
  ["POST", "/api/v1/model-configuration/draft/assignments/:target/validations", "core"],
  ["POST", "/api/v1/model-configuration/draft/assignments/:target/candidate-validations", "core"],
  ["GET", "/api/v1/model-configuration/draft/assignments/:target/candidate-validations/:validationId", "core"],
  ["POST", "/api/v1/model-configuration/draft/validations", "core"],
  ["POST", "/api/v1/model-configuration/apply", "core"],
  // Policy Library and Policy Studio exist only where Guardrails are authored.
  ["GET", "/api/v1/policies", "authoring"],
  ["GET", "/api/v1/guardrail-profiles", "authoring"],
  ["GET", "/api/v1/policy-catalog/protection-presets", "authoring"],
  ["GET", "/api/v1/policy-catalog/actions", "authoring"],
  ["GET", "/api/v1/policies/:id", "authoring"],
  ["POST", "/api/v1/policies", "authoring"],
  ["PATCH", "/api/v1/policies/:id", "authoring"],
  ["DELETE", "/api/v1/policies/:id", "authoring"],
  ["GET", "/api/v1/policies/:id/draft/checks", "authoring"],
  ["GET", "/api/v1/policies/:id/test-runs/latest", "authoring"],
  ["GET", "/api/v1/policies/:id/test-runs/:runId", "authoring"],
  ["POST", "/api/v1/policies/:id/test-runs", "authoring"],
  ["POST", "/api/v1/policies/:id/publish", "authoring"],
  ["GET", "/api/v1/authoring/capabilities", "authoring"],
  ["POST", "/api/v1/authoring/intent-analyses", "authoring"],
  ["POST", "/api/v1/authoring/document-analyses", "authoring"],
  ["POST", "/api/v1/authoring/plan-previews", "authoring"],
  // Playground: trying a draft is authoring; talking to a released version is not.
  ["GET", "/api/v1/playground/models", "core"],
  ["POST", "/api/v1/playground/guardrails/:guardrailId/draft-previews", "authoring"],
  ["POST", "/api/v1/playground/guardrails/:guardrailId/draft-interactions", "authoring"],
  ["POST", "/api/v1/playground/guardrails/:guardrailId/interactions", "core"],
  // Guardrails: drafts, tests and publication are authoring; released versions are core.
  ["GET", "/api/v1/guardrails", "core"],
  // Read-only Policies frozen in released versions; never the Library.
  ["GET", "/api/v1/released-policies", "core"],
  ["POST", "/api/v1/guardrails", "authoring"],
  ["GET", "/api/v1/guardrails/:id", "core"],
  ["GET", "/api/v1/guardrails/:id/package", "core"],
  ["POST", "/api/v1/guardrail-packages", "core"],
  ["GET", "/api/v1/guardrail-packages/:packageId", "core"],
  ["POST", "/api/v1/guardrail-packages/:packageId/imports", "core"],
  ["POST", "/api/v1/guardrails/:id/versions/:version/environment-check", "core"],
  ["POST", "/api/v1/guardrails/:id/duplicate", "authoring"],
  ["PATCH", "/api/v1/guardrails/:id", "authoring"],
  ["POST", "/api/v1/guardrails/:id/publish", "authoring"],
  ["GET", "/api/v1/guardrails/:id/draft-changes", "authoring"],
  ["POST", "/api/v1/guardrails/:id/discard-draft", "authoring"],
  ["GET", "/api/v1/guardrails/:id/versions/:version/deletion-impact", "core"],
  ["DELETE", "/api/v1/guardrails/:id/versions/:version", "core"],
  ["PUT", "/api/v1/guardrails/:id/latest-version", "core"],
  ["GET", "/api/v1/guardrails/:id/logging", "core"],
  ["PATCH", "/api/v1/guardrails/:id/logging", "core"],
  ["GET", "/api/v1/guardrails/:id/deletion-impact", "core"],
  ["DELETE", "/api/v1/guardrails/:id", "core"],
  ["GET", "/api/v1/guardrails/:guardrailId/test-cases", "core"],
  ["POST", "/api/v1/guardrails/:guardrailId/test-cases", "authoring"],
  ["DELETE", "/api/v1/guardrails/:guardrailId/test-cases/:caseId", "authoring"],
  ["PATCH", "/api/v1/guardrails/:id/test-scope", "authoring"],
  ["GET", "/api/v1/test-runs", "core"],
  ["GET", "/api/v1/test-runs/:runId", "core"],
  ["POST", "/api/v1/guardrails/:guardrailId/test-runs", "authoring"],
  ["GET", "/api/v1/endpoints", "core"],
  ["POST", "/api/v1/endpoints", "core"],
  ["GET", "/api/v1/endpoints/:id", "core"],
  ["PATCH", "/api/v1/endpoints/:id", "core"],
  ["POST", "/api/v1/endpoints/:id/credentials", "core"],
  ["DELETE", "/api/v1/endpoints/:id/credentials/:credentialId", "core"],
  ["GET", "/api/v1/endpoints/:id/deletion-impact", "core"],
  ["DELETE", "/api/v1/endpoints/:id", "core"],
  ["GET", "/api/v1/runner-pools", "core"],
  ["PATCH", "/api/v1/runner-pools/:id", "core"],
  ["DELETE", "/api/v1/runner-instances/:runnerId", "core"],
  ["GET", "/api/v1/routers", "core"],
  ["GET", "/api/v1/routers/:id", "core"],
  ["POST", "/api/v1/routers", "core"],
  ["PUT", "/api/v1/routers/:id/draft", "core"],
  ["DELETE", "/api/v1/routers/:id", "core"],
  ["POST", "/api/v1/routers/:id/publication-preview", "core"],
  ["GET", "/api/v1/routers/:id/change-requests", "core"],
  ["POST", "/api/v1/routers/:id/change-requests", "core"],
  ["GET", "/api/v1/routers/:id/change-requests/:changeId", "core"],
  ["POST", "/api/v1/routers/:id/change-requests/:changeId/approve", "core"],
  ["POST", "/api/v1/routers/:id/change-requests/:changeId/emergency-apply", "core"],
  ["POST", "/api/v1/routers/:id/change-requests/:changeId/reject", "core"],
  ["POST", "/api/v1/routers/:id/change-requests/:changeId/withdraw", "core"],
  ["POST", "/api/v1/routers/:id/change-requests/:changeId/revert", "core"],
  ["DELETE", "/api/v1/routers/:id/revisions/:revision", "core"],
  ["PUT", "/api/v1/routers/:id/endpoints", "core"],
  ["GET", "/api/v1/routers/:id/revisions", "core"],
  ["GET", "/api/v1/routers/:id/revisions/:revision", "core"],
  ["GET", "/api/v1/routers/:id/traffic-distribution", "core"],
  ["GET", "/api/v1/routers/:id/routes/:routeId/traffic-distribution", "core"],
  ["POST", "/api/v1/playground/path-tests", "core"],
  ["POST", "/api/v1/routers/:id/simulations", "core"],
  ["GET", "/api/v1/routing/selector-fields", "core"],
  ["GET", "/api/v1/telemetry/events", "core"],
  ["GET", "/api/v1/telemetry/events/:id", "core"],
  ["GET", "/api/v1/telemetry/endpoint-activity", "core"],
  ["GET", "/api/v1/telemetry/metrics", "core"],
  ["GET", "/api/v1/audit-events", "core"],
];

const patterns = routeCapabilities.map(([method, template, capability]) => ({
  method, capability, pattern: new RegExp(`^${template.replace(/:[^/]+/g, "[^/]+")}$`),
}));

/** Unlisted operations count as authoring, so a new route is denied until classified. */
export function routeCapability(method: string, path: string): "core" | "authoring" {
  return patterns.find(item => item.method === method && item.pattern.test(path))?.capability ?? "authoring";
}
