# @generated by scripts/generate_enforcement_action_contract.py
# Source: proto/tasklattice/guard/control/v1/enforcement_action.proto
#
# Closed Rule handling decisions shared by Controller and Runner. Detector implementation and application workflows are separate from these decisions. Declaration order is display order; the greatest numeric priority wins.
# Do not edit this file directly.

from __future__ import annotations

from types import MappingProxyType
from typing import Final, Literal, Mapping


# Closed wire values for a post-evaluation directive. This type is distinct
# from EvaluatorVerdict, PolicyDecision, and the Python Actions invoked by NeMo.
EnforcementAction = Literal[
    'allow',
    'block',
    'transform',
]

# Stable product display order; it has no conflict-resolution semantics.
ENFORCEMENT_ACTION_DISPLAY_ORDER: Final[tuple[EnforcementAction, ...]] = (
    'allow',
    'block',
    'transform',
)

# Canonical precedence used when independent evaluators request different actions.
ENFORCEMENT_ACTION_CONFLICT_ORDER: Final[tuple[EnforcementAction, ...]] = (
    'block',
    'transform',
    'allow',
)
ENFORCEMENT_ACTIONS: Final[frozenset[EnforcementAction]] = frozenset(
    ENFORCEMENT_ACTION_DISPLAY_ORDER
)

# Human-readable contract semantics. UI translations remain presentation data.
ENFORCEMENT_ACTION_DESCRIPTIONS: Final[Mapping[EnforcementAction, str]] = (
    MappingProxyType({
        'allow': "Keep the content unchanged and record evidence; never override another Rule's block.",
        'block': 'Stop the checked content. The caller owns refusal presentation and any subsequent workflow.',
        'transform': 'Continue only with a concrete replacement or valid content patches; missing output fails closed.',
    })
)

# Numeric precedence is useful for telemetry without making array order implicit.
ENFORCEMENT_ACTION_CONFLICT_PRIORITIES: Final[Mapping[EnforcementAction, int]] = (
    MappingProxyType({
        'allow': 100,
        'block': 800,
        'transform': 200,
    })
)
