# @generated by scripts/generate_enforcement_action_contract.py
# Source: proto/tasklattice/guard/control/v1/enforcement_action.proto
#
# Closed post-evaluation directives shared by Controller and Runner. This is not an evaluator verdict, a PolicyDecision, or a NeMo Action. Declaration order is the stable product display order. Non-zero numeric values are the canonical conflict priority: when independent evaluators request different actions, the action with the greatest number wins.
# Do not edit this file directly.

from __future__ import annotations

from types import MappingProxyType
from typing import Final, Literal, Mapping


# Closed wire values for a post-evaluation directive. This type is distinct
# from EvaluatorVerdict, PolicyDecision, and the Python Actions invoked by NeMo.
EnforcementAction = Literal[
    'reject',
    'redact',
    'rewrite',
    'regenerate',
    'redirect',
    'fallback',
    'clarify',
    'pass',
]

# Stable product display order; it has no conflict-resolution semantics.
ENFORCEMENT_ACTION_DISPLAY_ORDER: Final[tuple[EnforcementAction, ...]] = (
    'reject',
    'redact',
    'rewrite',
    'regenerate',
    'redirect',
    'fallback',
    'clarify',
    'pass',
)

# Canonical precedence used when independent evaluators request different actions.
ENFORCEMENT_ACTION_CONFLICT_ORDER: Final[tuple[EnforcementAction, ...]] = (
    'reject',
    'clarify',
    'fallback',
    'regenerate',
    'rewrite',
    'redirect',
    'redact',
    'pass',
)
ENFORCEMENT_ACTIONS: Final[frozenset[EnforcementAction]] = frozenset(
    ENFORCEMENT_ACTION_DISPLAY_ORDER
)

# Human-readable contract semantics. UI translations remain presentation data.
ENFORCEMENT_ACTION_DESCRIPTIONS: Final[Mapping[EnforcementAction, str]] = (
    MappingProxyType({
        'reject': 'Block the current phase. Do not call the model for rejected input or deliver rejected output.',
        'redact': 'Mask sensitive spans with reviewed replacements and continue with the transformed content.',
        'rewrite': 'Replace the current content with a complete reviewed replacement.',
        'regenerate': 'Ask the owner of the model lifecycle to generate a new response.',
        'redirect': 'Guide the interaction to an approved topic, flow, or replacement response.',
        'fallback': 'Use an approved fallback response or degraded execution path.',
        'clarify': 'Require more information from the user before the interaction continues.',
        'pass': 'Record the finding without intervening in the content.',
    })
)

# Numeric precedence is useful for telemetry without making array order implicit.
ENFORCEMENT_ACTION_CONFLICT_PRIORITIES: Final[Mapping[EnforcementAction, int]] = (
    MappingProxyType({
        'reject': 800,
        'redact': 200,
        'rewrite': 400,
        'regenerate': 500,
        'redirect': 300,
        'fallback': 600,
        'clarify': 700,
        'pass': 100,
    })
)
