# yaml-language-server: $schema=../../../schemas/rule.schema.json
id: code-injection-blocker/blocked-word-4
name: exec(
description: Code injection
stages:
- input
detector:
  ref: text/keyword
  version: 1.0.0
  parameters:
    keywords:
    - - exec(
      - medium
on_match:
  action: block
  replacement: null
runtime_adapter:
  binding_id: code-injection-blocker
  implementation_rule_id: blocked-word-4
metadata:
  taxonomy_ids:
  - TALI-TOOL-SECURITY-UNAUTHORIZED-EXECUTION
risk_level: high
