# yaml-language-server: $schema=../../../schemas/rule.schema.json
id: sql-injection-blocker/blocked-word-4
name: UNION SELECT
description: SQL injection
stages:
- input
detector:
  ref: text/keyword
  version: 1.0.0
  parameters:
    keywords:
    - - UNION SELECT
      - medium
on_match:
  action: reject
  replacement: null
runtime_adapter:
  binding_id: sql-injection-blocker
  implementation_rule_id: blocked-word-4
metadata:
  taxonomy_ids:
  - TALI-TOOL-SECURITY-UNAUTHORIZED-EXECUTION
risk_level: high
