INSERT INTO "guardrail_profile" ("id", "category", "category_name", "is_default", "sort_order", "definition") VALUES
('china-mainland-runtime', 'china_mainland', 'China mainland', true, 5, '{"version":"1.0.0","name":"China mainland runtime baseline","industry":"general","jurisdictions":["cn"],"description":"Local China-mainland identifier, credential and explicit Chinese prompt-manipulation controls. Broader content governance and generated-content labelling require separate integration.","policies":[{"policyId":"local-credentials","policyVersion":"2.0.0","enabledRails":["input","output"],"parameterValues":{}},{"policyId":"local-passports","policyVersion":"2.0.0","enabledRails":["input","output"],"parameterValues":{}},{"policyId":"china-personal-identifiers","policyVersion":"1.0.0","enabledRails":["input","output"],"parameterValues":{}},{"policyId":"china-prompt-manipulation","policyVersion":"1.0.0","enabledRails":["input"],"parameterValues":{}}],"suggestedTopics":[],"optionalPolicyIds":["builtin-content-safety","builtin-jailbreak","builtin-topic-safety","builtin-contextual-grounding","builtin-automated-reasoning","china-organization-identifiers"],"limitations":["Runtime Enforced: only the selected local identifier, credential and explicit prompt-manipulation patterns run without an external model.","Requires Integration: broader Chinese-language content-risk classification, grounding, generated-content visible and implicit labels, and authenticated transaction context require validated models or application/gateway integration.","Governance Only: filing, security assessment, training-data governance, lawful-basis and consent decisions, cross-border review, retention, human oversight and regulatory reporting are not automated by this Profile.","The jurisdiction label is deployment context, not a legal-scope decision, certification or proof of compliance with mainland-China law or standards.","Redaction can remove identifiers needed by an authorized workflow; use approved structured channels and review field-level handling instead of assuming text redaction is always appropriate."]}'::jsonb),
('china-banking-assistant', 'china_banking', 'China mainland banking', true, 6, '{"version":"1.0.0","name":"China mainland banking assistant","industry":"banking","jurisdictions":["cn"],"description":"China mainland runtime baseline plus bounded banking-assistant controls for credential theft, identity-check evasion and selected misleading return guarantees.","policies":[{"policyId":"local-credentials","policyVersion":"2.0.0","enabledRails":["input","output"],"parameterValues":{}},{"policyId":"local-passports","policyVersion":"2.0.0","enabledRails":["input","output"],"parameterValues":{}},{"policyId":"china-personal-identifiers","policyVersion":"1.0.0","enabledRails":["input","output"],"parameterValues":{}},{"policyId":"china-prompt-manipulation","policyVersion":"1.0.0","enabledRails":["input"],"parameterValues":{}},{"policyId":"china-banking-assistant-boundaries","policyVersion":"1.0.0","enabledRails":["input","output"],"parameterValues":{}}],"suggestedTopics":["账户、银行卡与支付","银行产品信息与风险教育","客户服务与反欺诈报告"],"optionalPolicyIds":["builtin-content-safety","builtin-jailbreak","builtin-topic-safety","builtin-contextual-grounding","builtin-automated-reasoning","china-organization-identifiers","securities-market-integrity"],"limitations":["Runtime Enforced: only the selected local identifier, credential and explicit prompt-manipulation patterns run without an external model.","Requires Integration: broader Chinese-language content-risk classification, grounding, generated-content visible and implicit labels, and authenticated transaction context require validated models or application/gateway integration.","Governance Only: filing, security assessment, training-data governance, lawful-basis and consent decisions, cross-border review, retention, human oversight and regulatory reporting are not automated by this Profile.","The jurisdiction label is deployment context, not a legal-scope decision, certification or proof of compliance with mainland-China law or standards.","Redaction can remove identifiers needed by an authorized workflow; use approved structured channels and review field-level handling instead of assuming text redaction is always appropriate.","Banking phrase checks do not make credit, suitability, KYC, AML, transaction-authorisation or fraud determinations and do not implement JR/T 0221-2021 evaluation procedures."]}'::jsonb)
ON CONFLICT ("id") DO UPDATE SET
  "category" = EXCLUDED."category",
  "category_name" = EXCLUDED."category_name",
  "is_default" = EXCLUDED."is_default",
  "sort_order" = EXCLUDED."sort_order",
  "definition" = EXCLUDED."definition",
  "updated_at" = now();
