# yaml-language-server: $schema=../../../schemas/rule.schema.json
id: pattern/ipv6
name: IP Address (IPv6)
description: Detects IPv6 addresses
stages:
- input
- output
detector:
  ref: text/regex
  version: 1.0.0
  parameters:
    expression: (?<![0-9a-fA-F:])(?:(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,7}:|:(?::[0-9a-fA-F]{1,4}){1,7}|::|(?:[0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,5}(?::[0-9a-fA-F]{1,4}){1,2}|(?:[0-9a-fA-F]{1,4}:){1,4}(?::[0-9a-fA-F]{1,4}){1,3}|(?:[0-9a-fA-F]{1,4}:){1,3}(?::[0-9a-fA-F]{1,4}){1,4}|(?:[0-9a-fA-F]{1,4}:){1,2}(?::[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:(?::[0-9a-fA-F]{1,4}){1,6})(?![0-9a-fA-F:])
on_match:
  action: transform
  replacement: '[ipv6_REDACTED]'
runtime_adapter:
  binding_id: local-network-addresses
  implementation_rule_id: ipv6
metadata:
  taxonomy_ids:
  - TALI-PRIVACY-PII
risk_level: medium
