{{- include "tali-guard.validateValues" . }}
{{- if and (not .Values.controlPlaneAgent.provider.existingSecret) .Values.controlPlaneAgent.provider.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tali-guard.controlPlaneAgentSecretName" . }}
  labels:
    {{- include "tali-guard.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.controlPlaneAgent.provider.secretKey }}: {{ .Values.controlPlaneAgent.provider.apiKey | quote }}
{{- end }}
