# yaml-language-server: $schema=../../../schemas/rule.schema.json
id: sg-pdpa-contact-information/email
name: Email Address
description: Detects email addresses
stages:
- input
detector:
  ref: text/regex
  version: 1.0.0
  parameters:
    expression: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
on_match:
  action: redact
  replacement: '[email_REDACTED]'
runtime_adapter:
  binding_id: sg-pdpa-contact-information
  implementation_rule_id: email
metadata:
  taxonomy_ids:
  - TALI-PRIVACY-PII
risk_level: medium
